-- 1. Create source table (simulating OLTP system)

CREATE OR REPLACE TABLE SRC_ORDERS (
  ORDER_ID      NUMBER,
  CUSTOMER_ID   NUMBER,
  ORDER_STATUS  STRING,
  ORDER_AMOUNT  NUMBER(10,2),
  ORDER_TS      TIMESTAMP_NTZ
);

-- Initial load
INSERT INTO SRC_ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_STATUS, ORDER_AMOUNT, ORDER_TS)
VALUES
  (1, 101, 'NEW',      100.00, '2025-12-19 09:00:00'),
  (2, 102, 'NEW',      250.00, '2025-12-19 09:05:00'),
  (3, 103, 'NEW',      300.00, '2025-12-19 09:10:00');

SELECT * FROM SRC_ORDERS ORDER BY ORDER_ID;

-- Create streams on the source

-- Standard stream (full CDC: insert, update, delete)
CREATE OR REPLACE STREAM S_ORDERS_STD
ON TABLE SRC_ORDERS;

-- Append-only stream (only new inserts)
CREATE OR REPLACE STREAM S_ORDERS_APPEND
ON TABLE SRC_ORDERS
APPEND_ONLY = TRUE;

-- Inspect stream definitions
SHOW STREAMS LIKE 'S_ORDERS%';

-- Generate some changes on source (INS / UPD / DEL)
-- Insert new orders
INSERT INTO SRC_ORDERS VALUES
  (4, 104, 'NEW',      180.00, '2025-12-19 09:20:00'),
  (5, 105, 'NEW',      500.00, '2025-12-19 09:25:00');

-- Update existing order
UPDATE SRC_ORDERS
SET ORDER_STATUS = 'SHIPPED',
    ORDER_AMOUNT = ORDER_AMOUNT + 20
WHERE ORDER_ID = 2;

-- Delete an order
DELETE FROM SRC_ORDERS
WHERE ORDER_ID = 3;

SELECT * FROM SRC_ORDERS ORDER BY ORDER_ID;

-- Inspect stream contents (what changed since creation)
-- 
-- Standard stream – shows INS/UPD/DEL
SELECT
  METADATA$ACTION           AS ACTION,      -- INSERT / DELETE
  METADATA$ISUPDATE         AS IS_UPDATE,   -- TRUE for UPDATE before/after
  METADATA$ROW_ID           AS ROW_ID,      -- Stable row id
  ORDER_ID,
  CUSTOMER_ID,
  ORDER_STATUS,
  ORDER_AMOUNT,
  ORDER_TS
FROM S_ORDERS_STD
ORDER BY ORDER_ID, ACTION;

-- Append-only stream – only inserts
SELECT
  METADATA$ACTION   AS ACTION,
  METADATA$ISUPDATE AS IS_UPDATE,
  ORDER_ID,
  CUSTOMER_ID,
  ORDER_STATUS,
  ORDER_AMOUNT,
  ORDER_TS
FROM S_ORDERS_APPEND
ORDER BY ORDER_ID;

-- Create target table for CDC (ODS layer)
CREATE OR REPLACE TABLE ODS_ORDERS AS
SELECT * FROM SRC_ORDERS;    -- initial snapshot / first load

SELECT * FROM ODS_ORDERS ORDER BY ORDER_ID;

-- 6. Single-run CDC MERGE using standard stream
--
-- This MERGE:
--   - Inserts new rows
--   - Updates changed rows
--   - Deletes removed rows
--   driven by S_ORDERS_STD stream metadata.

MERGE INTO ODS_ORDERS T
USING S_ORDERS_STD S
   ON T.ORDER_ID = S.ORDER_ID
WHEN MATCHED
     AND METADATA$ACTION = 'DELETE'
     AND METADATA$ISUPDATE = FALSE THEN
  DELETE
WHEN MATCHED
     AND METADATA$ACTION = 'INSERT'
     AND METADATA$ISUPDATE = TRUE THEN
  UPDATE SET
    T.CUSTOMER_ID  = S.CUSTOMER_ID,
    T.ORDER_STATUS = S.ORDER_STATUS,
    T.ORDER_AMOUNT = S.ORDER_AMOUNT,
    T.ORDER_TS     = S.ORDER_TS
WHEN NOT MATCHED
     AND METADATA$ACTION = 'INSERT'
     AND METADATA$ISUPDATE = FALSE THEN
  INSERT (ORDER_ID, CUSTOMER_ID, ORDER_STATUS, ORDER_AMOUNT, ORDER_TS)
  VALUES (S.ORDER_ID, S.CUSTOMER_ID, S.ORDER_STATUS, S.ORDER_AMOUNT, S.ORDER_TS);

-- After MERGE:
--   - Stream offset is advanced (changes consumed)
--   - Rerunning this MERGE immediately will be a no-op
SELECT * FROM ODS_ORDERS ORDER BY ORDER_ID;

-- Stream now empty (no more unconsumed changes)
SELECT COUNT(*) AS PENDING_CHANGES_FROM_STREAM
FROM S_ORDERS_STD;

-- Simulate more changes and re-run CDC

-- New changes after first MERGE
INSERT INTO SRC_ORDERS VALUES
  (6, 106, 'NEW',      700.00, '2025-12-19 09:40:00');

UPDATE SRC_ORDERS
SET ORDER_STATUS = 'CANCELLED'
WHERE ORDER_ID = 4;

DELETE FROM SRC_ORDERS
WHERE ORDER_ID = 1;

-- See what the stream now sees (only *new* changes)
SELECT
  METADATA$ACTION AS ACTION,
  METADATA$ISUPDATE AS IS_UPDATE,
  ORDER_ID,
  ORDER_STATUS
FROM S_ORDERS_STD
ORDER BY ORDER_ID, ACTION;

-- Apply second MERGE
MERGE INTO ODS_ORDERS T
USING S_ORDERS_STD S
   ON T.ORDER_ID = S.ORDER_ID
WHEN MATCHED
     AND METADATA$ACTION = 'DELETE'
     AND METADATA$ISUPDATE = FALSE THEN
  DELETE
WHEN MATCHED
     AND METADATA$ACTION = 'INSERT'
     AND METADATA$ISUPDATE = TRUE THEN
  UPDATE SET
    T.CUSTOMER_ID  = S.CUSTOMER_ID,
    T.ORDER_STATUS = S.ORDER_STATUS,
    T.ORDER_AMOUNT = S.ORDER_AMOUNT,
    T.ORDER_TS     = S.ORDER_TS
WHEN NOT MATCHED
     AND METADATA$ACTION = 'INSERT'
     AND METADATA$ISUPDATE = FALSE THEN
  INSERT (ORDER_ID, CUSTOMER_ID, ORDER_STATUS, ORDER_AMOUNT, ORDER_TS)
  VALUES (S.ORDER_ID, S.CUSTOMER_ID, S.ORDER_STATUS, S.ORDER_AMOUNT, S.ORDER_TS);

SELECT * FROM ODS_ORDERS ORDER BY ORDER_ID;

-- 8. Streams + Tasks – automated CDC every 5 minutes

-- NOTE: Requires a warehouse (replace MY_WH with your actual warehouse)

CREATE OR REPLACE TASK T_ORDERS_CDC
  WAREHOUSE = WH_REPORTING
  SCHEDULE  = '5 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('S_ORDERS_STD')
AS
MERGE INTO ODS_ORDERS T
USING S_ORDERS_STD S
   ON T.ORDER_ID = S.ORDER_ID
WHEN MATCHED
     AND METADATA$ACTION = 'DELETE'
     AND METADATA$ISUPDATE = FALSE THEN
  DELETE
WHEN MATCHED
     AND METADATA$ACTION = 'INSERT'
     AND METADATA$ISUPDATE = TRUE THEN
  UPDATE SET
    T.CUSTOMER_ID  = S.CUSTOMER_ID,
    T.ORDER_STATUS = S.ORDER_STATUS,
    T.ORDER_AMOUNT = S.ORDER_AMOUNT,
    T.ORDER_TS     = S.ORDER,
    WHEN NOT MATCHED
     AND METADATA$ACTION = 'INSERT'
     AND METADATA$ISUPDATE = FALSE THEN
  INSERT (ORDER_ID, CUSTOMER_ID, ORDER_STATUS, ORDER_AMOUNT, ORDER_TS)
  VALUES (S.ORDER_ID, S.CUSTOMER_ID, S.ORDER_STATUS, S.ORDER_AMOUNT, S.ORDER_TS);

ALTER TASK T_ORDERS_CDC RESUME;



-- 9. CHANGES clause – ad-hoc CDC without a stream

SELECT
  METADATA$ACTION,
  METADATA$ISUPDATE,
  ORDER_ID,
  CUSTOMER_ID,
  ORDER_STATUS,
  ORDER_AMOUNT,
  ORDER_TS
FROM SRC_ORDERS
CHANGES (INFORMATION => DEFAULT)
AT  (TIMESTAMP => '2025-12-19 09:00:00'::TIMESTAMP_NTZ)
END (TIMESTAMP => '2025-12-19 10:00:00'::TIMESTAMP_NTZ)
ORDER BY ORDER_ID, METADATA$ACTION;

-- Append-only CHANGES (only inserts)
SELECT
  METADATA$ACTION,
  ORDER_ID,
  ORDER_STATUS
FROM SRC_ORDERS
CHANGES (INFORMATION => APPEND_ONLY)
AT  (TIMESTAMP => '2025-12-19 09:00:00'::TIMESTAMP_NTZ)
END (TIMESTAMP => '2025-12-19 10:00:00'::TIMESTAMP_NTZ);


